INSERT INTO USERS (USERNAME, PASSWORD, ENABLED)
VALUES ('user', 'user', true);

INSERT INTO USERS (USERNAME, PASSWORD, ENABLED)
VALUES ('admin', 'admin', true);

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
VALUES ('user', 'ROLE_USER');

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
VALUES ('admin', 'ROLE_ADMIN');